config/routes.rb
Metrix::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users
  resources :roles
  resources :servers do
    get 'import', :on => :member
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, Server
    if (user.has_role? :admin) or (user.name=='admin')
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :server
  
  attr_accessible :name, :server
  
  validates_presence_of :name, :server
  validates_uniqueness_of :name, :case_sensitive => false, :scope => :server

  def self.create(server, project_name)
    @project = Project.new
    @project.server = server
    @project.name = project_name
    if @project.save
      return true
    else
      return false
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  attr_accessible :name

  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false

  scopify
end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :projects, :dependent => :restrict
  
  attr_accessible :name, :url, :username, :password

  validates_presence_of :name, :url, :username, :password
  validates_uniqueness_of :name, :case_sensitive => false
  validates_uniqueness_of :url, :case_sensitive => false
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  validates_presence_of :name, :email, :encrypted_password
  validates_uniqueness_of :name, :case_sensitive => false
  validates_uniqueness_of :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @roles = Role.all
  end
  
  def new
    @role = Role.new
  end

  def create
    @role = Role.new params[:role]
    if @role.save
      redirect_to roles_path
    else
      render :action => 'new'
    end
  end

  def edit
    @role = Role.find params[:id]
  end

  def update
    @role = Role.find params[:id]
    if @role.update_attributes params[:role]
      redirect_to roles_path
    else
      render :action => :edit
    end
  end

  def destroy
    @role = Role.find params[:id]
    if @role.users.empty?
      @role.destroy
      redirect_to roles_path
    else
      redirect_to roles_path, :flash => { :error => "Cannot delete a role which is currently assigned to a user." }
    end
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @servers = Server.all
  end
  
  def new
    @server = Server.new
  end

  def create
    @server = Server.new params[:server]
    if @server.save
      redirect_to servers_path
    else
      render :action => 'new'
    end
  end

  def edit
    @server = Server.find params[:id]
  end

  def update
    @server = Server.find params[:id]
    if @server.update_attributes params[:server]
      redirect_to servers_path
    else
      render :action => :edit
    end
  end

  def destroy
    @server = Server.find params[:id]
    if @server.projects.empty?
      @server.destroy
      redirect_to servers_path
    else
      redirect_to servers_path, :flash => { :error => "Cannot delete a server which is referenced by a project." }      
    end
  end

  def import
    # TODO: Flash message "Import running ..."
    @server = Server.find params[:id]
    gerrit = Gerry.new(@server.url, @server.username, @server.password)
    projects_list = gerrit.projects

    projects_list.values.each { |p|
      project_name = p["id"]
      if !Project.find_by_server_id_and_name(@server, project_name)
        if !Project.create(@server, project_name)
          # TODO: Handle failing save
        end
      end
#      query_string = "q=status:merged+project:#{project_name}+-age:1week&o=ALL_REVISIONS&o=ALL_COMMITS&o=DETAILED_LABELS&o=DETAILED_ACCOUNTS&o=CURRENT_FILES"
      query_string = "q=status:merged+project:#{project_name}+-age:1month&o=ALL_REVISIONS&o=ALL_COMMITS&o=DETAILED_LABELS&o=DETAILED_ACCOUNTS&o=CURRENT_FILES"
      project_changes = gerrit.changes([query_string])
    }

    redirect_to servers_path, :flash => { :notice => "Import successful." }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/home/index.html.erb
<h3>Metrix</h3>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Metrix", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
      <li>
      <%= link_to 'Servers', servers_path %>
      </li>
    <% if (current_user.has_role? :admin) or (current_user.name=='admin') %>
      <li>
      <%= link_to 'Users', users_path %>
      </li>
      <li>
      <%= link_to 'Roles', roles_path %>
      </li>
    <% end %>
    <li>
    <%= link_to "Edit [#{current_user.name}]", edit_user_registration_path %>
    </li>
    <li>
    <%= link_to "Logout [#{current_user.name}]", destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Metrix" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Metrix" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/roles/_form.html.erb
<%= simple_form_for(@role, :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>
  <%= display_base_errors @role %>
  <%= f.input :name, :required => true, :autofocus => true %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to "Cancel", :back, :class => 'btn' %>
<% end %>

app/views/roles/edit.html.erb
<h2>Edit role</h2>
<%= render :partial => 'form' %>

app/views/roles/index.html.erb
<h3>Roles</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
  <% @roles.each do |role| %>
    <tr>
      <td><%= role.name %></td>
      <td><% if role.name != 'admin' %>
            <%= link_to("Edit", edit_role_path(role), :class => 'btn btn-mini') %>
            <% if role.users.empty? %>
              <%= link_to("Delete", role_path(role), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') %>
            <% end %>
          <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Create new', new_role_path, :class => 'btn btn-primary' %>

</div>

app/views/roles/new.html.erb
<h2>Create role</h2>
<%= render :partial => 'form' %>

app/views/servers/_form.html.erb
<p><i>Important! Server must be running min. Gerrit version 2.6!</i></p>
<%= simple_form_for(@server, :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>
  <%= display_base_errors @server %>
  <%= f.input :name, :required => true, :autofocus => true %>
  <%= f.input :url, :required => true, :hint => "no '/' at the end" %>
  <%= f.input :username, :required => true %>
  <%= f.input :password, :required => true, :label => 'HTTP password' %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to "Cancel", :back, :class => 'btn' %>
<% end %>

app/views/servers/edit.html.erb
<h2>Edit server</h2>
<%= render :partial => 'form' %>

app/views/servers/index.html.erb
<h3>Servers</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <% if current_user.has_role? :admin %>
      <th>Username</th>
      <th>HTTP password</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @servers.each do |server| %>
    <tr>
      <td><%= server.name %></td>
      <td><%= server.url %></td>
      <% if current_user.has_role? :admin %>
      <td><%= server.username %></td>
      <td><%= server.password %></td>
      <td>
        <%= link_to("Import", import_server_path(server), :method => :get, :class => 'btn btn-mini') %>
        <%= link_to("Edit", edit_server_path(server), :class => 'btn btn-mini') %>
        <% if server.projects.empty? %>
          <%= link_to("Delete", server_path(server), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') %>
        <% end %>
      </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Create new', new_server_path, :class => 'btn btn-primary' %>

</div>

app/views/servers/new.html.erb
<h2>Create server</h2>
<%= render :partial => 'form' %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
        <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Username: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>